name: Build APK

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANDROIDSDK: $HOME/android-sdk
      ANDROIDNDK: $HOME/android-sdk/ndk-bundle
      ANDROIDAPI: 33
      ANDROIDMINAPI: 21

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip python3-setuptools python3-wheel git zip
          pip install --upgrade pip
          pip install buildozer cython

      - name: Install Android SDK/NDK
        run: |
          sudo apt install -y openjdk-17-jdk unzip
          mkdir -p $HOME/android-sdk
          cd $HOME/android-sdk

          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdtools.zip
          unzip cmdtools.zip -d cmdline-tools-temp
          mkdir -p cmdline-tools/latest
          mv cmdline-tools-temp/cmdline-tools/* cmdline-tools/latest/
          rm -rf cmdline-tools-temp

          yes | cmdline-tools/latest/bin/sdkmanager --licenses --sdk_root=$HOME/android-sdk
          yes | cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/android-sdk "platform-tools"
          yes | cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/android-sdk "platforms;android-33"
          yes | cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/android-sdk "build-tools;36.1.0"
          yes | cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/android-sdk "ndk;25.2.9519653"

      - name: Force Buildozer to use external SDK
        run: |
          echo "[android]" > android_config.txt
          echo "sdk_dir = /home/runner/android-sdk" >> android_config.txt
          echo "ndk_dir = /home/runner/android-sdk/ndk-bundle" >> android_config.txt
          echo "android_api = 33" >> android_config.txt
          echo "android_minapi = 21" >> android_config.txt
          echo "use_android_sdk = True" >> android_config.txt
          echo "android.accept_sdk_license = True" >> android_config.txt
          echo "android.build_tools_version = 36.1.0" >> android_config.txt

          cat android_config.txt >> buildozer.spec

      - name: DELETE Buildozer internal SDK BEFORE build
        run: |
          rm -rf /home/runner/.buildozer/android/platform/android-sdk
          rm -rf /home/runner/.buildozer/android/platform/android-ndk*

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: ArtCrawler-APK
          path: bin/*.apk
ArtCrawler-APK
          path: bin/*.apk
